version: '3'

services:
  productdb:
    container_name: productdb
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - productdb:/var/lib/mysql
  orderdb:
    container_name: orderdb
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3307:3306'
    volumes:
      - orderdb:/var/lib/mysql

  paymentdb:
    container_name: paymentdb
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: paymentdb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3308:3306'
    volumes:
      - paymentdb:/var/lib/mysql

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

volumes:
  productdb:
    driver: local
  orderdb:
    driver: local
  paymentdb:
    driver: local
