server:
  port: 9296

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisRivera170/dcb-spring-app-config
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
