server:
  port: 9296

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisRivera170/dcb-spring-app-config
          clone-on-start: true
